Repository microsoft/Detours, pull requests merged in 2021-01, with the labels that each got.

#108 Allow compilation with MinGW to succeed
  src/detours.h
  src/image.cpp
  src/modules.cpp
Labels: enhancement

#140 Fix can not createwith some protected exe
  src/uimports.cpp
Labels: bug

#164 CI: `git checkout HEAD^2` step is no longer necessary
  .github/workflows/main.yml
Labels: bug

#165 CI: Follow major version of ilammy/msvc-dev-cmd to get latest fixes
  .github/workflows/main.yml
Labels: auto-merge

#166 Maintenance: Clean up some compiler warnings
  src/creatwth.cpp
  src/uimports.cpp
Labels: auto-merge, bug

#167 Minor fixes in symtest example
  samples/findfunc/symtest.cpp
Labels: auto-merge, bug

#168 Maintenance: Revert boolean flip
  src/uimports.cpp
Labels: auto-merge, bug
