Repository microsoft/Detours, pull requests merged in 2021-04, with the labels that each got.

#192 Fix Compiler Warnings
  src/creatwth.cpp
  src/detours.cpp
  src/disasm.cpp
Labels: enhancement, needs-attention :wave:

#193 Revert "Fix Compiler Warnings"
  src/creatwth.cpp
  src/detours.cpp
  src/disasm.cpp
Labels: bug

#143 Fix: Delete payload after finish associated task
  src/creatwth.cpp
  src/detours.cpp
  src/detours.h
  src/modules.cpp
Labels: bug

#194 Maintenance: Add .editorconfig file to try to standardize formatting.
  .editorconfig
Labels: auto-merge, enhancement
