Repository microsoft/Detours, pull requests merged in 2021-03, with the labels that each got.

#175 Enable debug logging on 'Debug' build configs
  .github/workflows/main.yml
  samples/common.mak
  src/Makefile
  src/creatwth.cpp
  src/detours.cpp
  src/modules.cpp
  src/uimports.cpp
  system.mak
Labels: bug, enhancement

#178 Feature: Add safe DetoursAttach (and friends) overloads
  samples/Makefile
  samples/simple_safe/Makefile
  samples/simple_safe/simple_safe.cpp
  samples/simple_safe/simple_safe.rc
  samples/simple_safe/sleep5.cpp
  src/detours.h
  vc/Detours.vcxproj
  vc/Detours.vcxproj.filters
Labels: enhancement, needs-author-feedback

#179 CI: Only run CodeQL for Debug matrix configuration
  .github/workflows/main.yml
Labels: auto-merge, enhancement

#180 Feature: Backport DetourAttach overloads to C++11
  src/detours.h
Labels: enhancement

#182 Fix potential integer overflow
  src/detours.h
  src/uimports.cpp
Labels: bug

#177 Fix + Tests: Add more tests covering the modules API, fix error handling bug that were found.
  src/modules.cpp
  tests/test_module_api.cpp
Labels: auto-merge, bug, enhancement

#81 Feature: Add DetourFindRemotePayload and improve other payload-related methods
  samples/Makefile
  samples/payload/Makefile
  samples/payload/payload.cpp
  samples/payload/payloadguid.hpp
  samples/payload/payloadtarget.cpp
  src/creatwth.cpp
  src/detours.cpp
  src/detours.h
  src/image.cpp
  src/modules.cpp
  tests/Makefile
  tests/payload.cpp
  tests/payload.h
  tests/process_helpers.cpp
  tests/process_helpers.h
  tests/test_module_api.cpp
Labels: enhancement

#184 Fix: Address print strings regression from PR #175
  src/creatwth.cpp
  src/detours.cpp
  src/modules.cpp
  src/uimports.cpp
Labels: bug

#187 Maintenance: Fix incorrect use of NULL to initialize DWORD
  src/creatwth.cpp
Labels: auto-merge, bug
